DELETE FROM SYS_MODULES where code = '011';
INSERT INTO SYS_MODULES(CODE,NAME,MENU,URL,OBJ,CREATOR,LASTUPD,ORDERNO,NOTE) 
VALUES ('011', '从OA导入报销流程', '业务模块', 'zdcwImpFromOA','ZDCW_IMP_FROM_OA','[admin]管理员','[admin]管理员',3,'从OA导入报销!');

DELETE FROM SYS_MODULES_RIGHTS where code like '011%';
/*011*/
INSERT INTO SYS_MODULES_RIGHTS(CODE,NAME,MODULES,LASTUPD)
select CONCAT(`CODE`,'001'), '查看权', CONCAT('[',`CODE`,']',`NAME`),'[admin]管理员' from sys_modules where code = '011';
INSERT INTO SYS_MODULES_RIGHTS(CODE,NAME,MODULES,LASTUPD)
select CONCAT(`CODE`,'002'), '搜索权', CONCAT('[',`CODE`,']',`NAME`),'[admin]管理员' from sys_modules where code = '011';
INSERT INTO SYS_MODULES_RIGHTS(CODE,NAME,MODULES,LASTUPD)
select CONCAT(`CODE`,'003'), '生成单据权', CONCAT('[',`CODE`,']',`NAME`),'[admin]管理员' from sys_modules where code = '011';



DROP TABLE IF EXISTS `ZDCW_IMP_FROM_OA`;
CREATE TABLE `ZDCW_IMP_FROM_OA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ORG` VARCHAR(255) NOT NULL,
  `OA_DEPTID` INT(11) NOT NULL,
  `OA_DEPT` VARCHAR(200) NOT NULL,
  `OA_FLOWID` INT(11) NOT NULL,
  `OA_FLOWNAME` VARCHAR(200) NOT NULL,
  `CONDITION` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

