DROP TABLE IF EXISTS `SYS_USER`;
CREATE TABLE `SYS_USER` (
  `CODE` VARCHAR(60) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `PASSWD` VARCHAR(255) NOT NULL,
  `ROLE` TEXT,
  `ORG` TEXT,
  `MOBILE` VARCHAR(255) NULL,
  `EMAIL` VARCHAR(255) NULL,
  `BANK` VARCHAR(255) NULL,
  `ACCOUNT` VARCHAR(255) NULL,
  `STAT` VARCHAR(255) NOT NULL DEFAULT '禁用',
  `CHECKSTAT` VARCHAR(255) NOT NULL DEFAULT '未复核',
  `NOTE` TEXT,
  `CREATOR` VARCHAR(160) NOT NULL,
  `CREATETIME` DATETIME NOT NULL DEFAULT NOW(),
  `LASTUPD` VARCHAR(160) NOT NULL,
  `LASTUPDTIME` DATETIME NOT NULL DEFAULT NOW(),
  `ORDERNO` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`CODE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
