DROP TABLE IF EXISTS `SYS_MODULES_RIGHTS`;
CREATE TABLE `SYS_MODULES_RIGHTS` (
  `CODE` VARCHAR(60) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `MODULES` VARCHAR(160) NOT NULL,
  `NOTE` TEXT,
  `LASTUPD` VARCHAR(160) NOT NULL,
  `LASTUPDTIME` DATETIME NOT NULL DEFAULT NOW(),
  `ORDERNO` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`CODE`), UNIQUE (`NAME`, `MODULES`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
