DROP TABLE IF EXISTS `SYS_STAT`;
CREATE TABLE `SYS_STAT` (
  `CODE` VARCHAR(60) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `FIREACT` VARCHAR(100) NOT NULL,
  `FIRESTAT` VARCHAR(100) NOT NULL,
  `CREATOR` VARCHAR(160) NOT NULL,
  `CREATETIME` DATETIME NOT NULL DEFAULT NOW(),
  `LASTUPD` VARCHAR(160) NOT NULL,
  `LASTUPDTIME` DATETIME NOT NULL DEFAULT NOW(),
  `ORDERNO` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`CODE`), UNIQUE (`NAME`), UNIQUE (`FIREACT`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
