DROP TABLE IF EXISTS `SYS_MODULES`;
CREATE TABLE `SYS_MODULES` (
  `CODE` VARCHAR(60) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `MENU` VARCHAR(255) NOT NULL,
  `URL` VARCHAR(255) NOT NULL,
  `OBJ` VARCHAR(255) NOT NULL,
  `NOTE` TEXT,
  `CREATOR` VARCHAR(160) NOT NULL,
  `CREATETIME` DATETIME NOT NULL DEFAULT NOW(),
  `LASTUPD` VARCHAR(160) NOT NULL,
  `LASTUPDTIME` DATETIME NOT NULL DEFAULT NOW(),
  `ORDERNO` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`CODE`), UNIQUE (`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
