DROP TABLE IF EXISTS `ZDCW_PAYMENT_MASTER`;
CREATE TABLE `ZDCW_PAYMENT_MASTER` (
  `NUM` VARCHAR(60) NOT NULL,
  `ORG` VARCHAR(160) NOT NULL,
  `BILLNUM` VARCHAR(60) NOT NULL,
  `STAT` VARCHAR(255) NOT NULL,
  `INPUTTER` VARCHAR(160) NOT NULL,
  `INPUTTIME` DATETIME NOT NULL,
  `CHECKER` VARCHAR(160) NULL,
  `CHECKTIME` DATETIME NULL,
  `APPROVER` VARCHAR(160) NULL,
  `APPROVETIME` DATETIME NULL, 
  `NOTE` TEXT,
  PRIMARY KEY (`NUM`), UNIQUE (`ORG`, `BILLNUM`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
