DROP TABLE IF EXISTS `biz_payee`;
CREATE TABLE `biz_payee` (
  `CODE` varchar(60) NOT NULL,
  `NAME` varchar(100) NOT NULL,
  `ORG` varchar(160) NOT NULL,
  `BANK` varchar(255) DEFAULT NULL,
  `ACCOUNT` varchar(255) NOT NULL DEFAULT '',
  `NOTE` text,
  `CREATOR` varchar(160) NOT NULL,
  `CREATETIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LASTUPD` varchar(160) NOT NULL,
  `LASTUPDTIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ORDERNO` int(11) NOT NULL DEFAULT '0',
  `CHECKSTAT` varchar(255) NOT NULL DEFAULT '未复核',
  `MOBILE` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `CONTACTS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CODE`),
  UNIQUE KEY `NAME` (`NAME`,`ORG`,`ACCOUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
