DROP TABLE IF EXISTS `SYS_SETTING`;
CREATE TABLE `SYS_SETTING` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STYPE` VARCHAR(60) NOT NULL DEFAULT 'public',
  `SNAME` VARCHAR(255) NOT NULL,
  `SVALUE` VARCHAR(255) NOT NULL DEFAULT '',
  `NOTE` TEXT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
