DROP TABLE IF EXISTS `SYS_LOG`;
CREATE TABLE `SYS_LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `OPER` VARCHAR(160) NOT NULL,
  `OPERTIME` DATETIME NOT NULL DEFAULT NOW(),
  `OBJ` VARCHAR(255) NOT NULL,
  `OPERTYPE` VARCHAR(255) NOT NULL,
  `CONTENT` TEXT,
  `NOTE` TEXT,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;