DROP TABLE IF EXISTS `SYS_AUTH`;
CREATE TABLE `SYS_AUTH` (
  `ROLE` VARCHAR(160) NOT NULL,
  `RIGHTS` VARCHAR(160) NOT NULL,
  `NOTE` TEXT,
  `LASTUPD` VARCHAR(160) NOT NULL,
  `LASTUPDTIME` DATETIME NOT NULL DEFAULT NOW(),
  `ORDERNO` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ROLE`, `RIGHTS`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
