DROP TABLE IF EXISTS `ZDCW_PAYMENT_DETAIL`;
CREATE TABLE `ZDCW_PAYMENT_DETAIL` (
  `NUM` VARCHAR(60) NOT NULL,
  `ITEMNO` VARCHAR(10) NOT NULL,
  `ORG` VARCHAR(160) NOT NULL,
  `APPLICANT` VARCHAR(160) NOT NULL,
  `PAYMENT` TEXT,
  `TOTALAMT` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `PAYEE` VARCHAR(160) NOT NULL,
  `BANK` VARCHAR(255) NOT NULL,
  `ACCOUNT` VARCHAR(255) NOT NULL,
  `NOTE` TEXT,
  `PAYSTAT` VARCHAR(255) NOT NULL DEFAULT '未付款',
  `PAYER` VARCHAR(160) NULL,
  `PAYTIME` DATETIME NULL,
  PRIMARY KEY (`NUM`,`ITEMNO`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
