DROP TABLE IF EXISTS `ZDCW_PAYMENT_LOCAL_OA `;
CREATE TABLE `ZDCW_PAYMENT_LOCAL_OA ` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ORG` VARCHAR(255) NOT NULL,
  `OA_FLOWID` INT(11) NOT NULL,
  `OA_FLOWNAME` VARCHAR(200) NOT NULL,
  `OA_DEPTID` INT(11) NOT NULL,
  `OA_DEPT` VARCHAR(200) NOT NULL,
  `CONDITION` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;
